log_level="info"

[server]
address = ":8082"
read_timeout = "5s"
write_timeout = "5s"

[messenger.pinpoint]
config = '''
{
    "app_id": "",
    "access_key": "",
    "secret_key": "",
    "region": "",
    "message_type": "",
    "sender_id": ""
}
'''

[messenger.ses]
config = '''
{
    "access_key": "",
    "secret_key": "",
    "region": ""
}
'''
[messenger.twilio]
config = '''
{
    "account_id": "",
    "auth_token": "",
    "sender_id": "",
    "upload_path": "",
}
'''
